name: Docker Build and Publish

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: 'Action'
        default: 'Build And Publish Docker Image'
        required: true

env:
  AZURE_CHATGTP_REPOSITORY: 'microsoft/azurechatgpt'
  COMMIT_SHA: '9def0d69d84d7a9bf99b11b8b447b381ab1cbc23'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.AZURE_CHATGTP_REPOSITORY }}
          ref: ${{ env.COMMIT_SHA }}

      - name: Convert GitHub Actor to Lowercase
        run: |
          echo "GITHUB_ACTOR_LOWER=$(('${{ env.GITHUB_ACTOR }}').ToLower())" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          echo "SHORT_COMMIT_SHA=$(('${{ env.COMMIT_SHA }}').Substring(0, 7))" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Debug Pipeline Variables
        run: |
          echo "Debug Pipeline Variables"
          echo "GITHUB_ACTOR_LOWER: ${{ env.GITHUB_ACTOR_LOWER }}"
          echo "GH_TOKEN_PACKAGES_WRITE (This should be redacted): ${{ secrets.GH_TOKEN_PACKAGES_WRITE }}"
        shell: pwsh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_ACTOR_LOWER }}
          password: ${{ secrets.GH_TOKEN_PACKAGES_WRITE }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          push: true
          tags: ghcr.io/${{ env.GITHUB_ACTOR_LOWER }}/${{ env.AZURE_CHATGTP_REPOSITORY }}:${{ env.SHORT_COMMIT_SHA }} # Tagging with the shortened commit SHA
